### ISSUE TITLE
If not already logged in, must click login again

### ISSUE THREAD

**Issue by matthewmp** [kennetpostigo/react-facebook-login-component#16]
Hi I noticed that if a user is not already logged into FB and they click the button to login, it will show a FB popup.  Once they submit that login another window opens that is blank.  When I close that window the FB popup is still there and needs to be closed.  Once closed the response to the FB login wont fire unless I press the login button again.  If the user was already logged in to FB it works as expected.  Any idea how to stop that second window from opening?

**Comment by wal-junaid** [comment]
Having an issue with the Facebook login I have to click twice on Facebook login button.
it will show an FB pop-up. Once they submit that login another window opens that is blank.  Once closed the response to the FB login won't fire unless I press the login button again.

**Comment by koss-lebedev** [comment]
@mmpal78  That was resolved in version 0.9.1, please update your package.json :)
