### ISSUE TITLE
can't retreive expires_in token property

### ISSUE THREAD

**Issue by alecchisi** [kennetpostigo/react-facebook-login-component#24]
from the response fields I can't retreive the token expiration time, is there a way to access `authResponse` object fields directly?

**Comment by koss-lebedev** [comment]
Hey @alecchisi ,

can you access it through `FB.getAuthResponse()`?

**Comment by alecchisi** [comment]
Probably yes, but that means I have to import Facebook SDK in my component, so why should I use the FacebookLogin component to wrap the login flow? :)

**Comment by alecchisi** [comment]
By the way, I found another component that wraps the whole element, so I'll use that one, thank you.

**Comment by koss-lebedev** [comment]
@alecchisi Facebook SDK is included within FacebookLogin component, and it creates a globally accessible FB object, so you don't have to include it manually
