### ISSUE TITLE
With some Facebook accounts the api response not return email field

### ISSUE THREAD

**Issue by dmoli** [kennetpostigo/react-facebook-login-component#26]
Hi, I have a doubt:

With some Facebook accounts, **the email field is not present in the response** after click Facebook login. And with others accounts the **email field is present**...

Some idea? why happen this?

Thanks!

**Comment by koss-lebedev** [comment]
Hi there,

Since it's an intermittent behavior, I have two guesses - either there are some issues with Facebook's Graph API (this happened to me in the past), or users remove "read email" permissions in the OAuth dialog window.

**Comment by dmoli** [comment]
@koss-lebedev thanks for your response.

My solution was a `try/catch` in the response callback function of facebook login. And if the email is not present, I throw a new error.

Thanks!
