### ISSUE TITLE
Auto Login without enter password

### ISSUE THREAD

**Issue by mrjosshi** [kennetpostigo/react-facebook-login-component#28]
Once I have logged-In through Facebook and logout. while at the time of login again it didn't asked me for Facebook password and logged in due to cookies. How to prevent this Please help.

Note: I Became logged out from Facebook

**Comment by kennetpostigo** [comment]
Not sure this is relevant to this component, the component itself doesn't set any cookies. Cookie is set through facebook SDK. We pass all props passed in so I would suggest you look through SDK documentation.

**Comment by mrjosshi** [comment]
ok Many thanks
