### ISSUE TITLE
Cannot use 'data-size' to style the button properly

### ISSUE THREAD

**Issue by seenickcode** [kennetpostigo/react-facebook-login-component#5]
Hello, I wanted to know how to style the button using what FB provides such as:

```
<div class="fb-login-button" data-max-rows="1" data-size="xlarge" data-show-faces="false" data-auto-logout-link="false"></div>
```

**Comment by kennetpostigo** [comment]
@seenickcode I didn't add this to the component mainly because I didn't want fb styles. However feel free to submit a PR if you'd like to include them if you need them urgently. I can't promise to add them in a timely manner because i'm swamped at work.

**Comment by seenickcode** [comment]
Ok thanks for the quick response.
