### ISSUE TITLE
cannot retrieving any data

### ISSUE THREAD

**Issue by addingama** [kennetpostigo/react-facebook-login-component#6]
Hi, 

I've tried your component but only the access token can be retrieved.
The error is 

```
(#100) Tried accessing nonexisting field (undefined) on node type (User)
````

my code 

```
<FacebookLogin socialId="myapp id"
                    language="en_US"
                    scope="email, user_friends"
                    responseHandler={this.responseFacebook}
                    xfbml={true}
                    version="v2.5"
                    class="facebook-login"
                    buttonText="Login With Facebook" />
```

can you help me

**Comment by kennetpostigo** [comment]
hey @dashracer ! 

I recently ran into this myself a week ago. I found [this](http://stackoverflow.com/questions/28617014/facebookgraphapierror-100-tried-accessing-nonexisting-field-user-photos-on). Basically to use some permissions for facebook login you . need to have your app reviewed before using in public in production or testing.

**Comment by kennetpostigo** [comment]
If you try just `scope="email"`, it should return the access token to you.

**Comment by addingama** [comment]
Hey @kennetpostigo ,

After looking at your source code, I think you forgot to add a parameter in your example.
```
<FacebookLogin socialId="yourAppID"
                       language="en_US"
                       scope="public_profile,email"
                       responseHandler={this.responseFacebook}
                       xfbml={true}
                       version="v2.5"
                       class="facebook-login"
                       buttonText="Login With Facebook"/>
```

But it should have param "fields"
```
<FacebookLogin socialId="yourAppID"
                       language="en_US"
                       scope="public_profile,email"
                       fields="id,name,email"
                       responseHandler={this.responseFacebook}
                       xfbml={true}
                       version="v2.5"
                       class="facebook-login"
                       buttonText="Login With Facebook"/>
```

If I add that param then the login page returning my name and email 


BTW, thanks for the component

**Comment by kennetpostigo** [comment]
@dashracer It would be an awesome contribution if you would like to submit a PR, I'm a little swamped at work at the moment.

**Comment by addingama** [comment]
I already done that :D @kennetpostigo

**Comment by kennetpostigo** [comment]
@dashracer merged!

**Comment by addingama** [comment]
Thanks !

I'm going to try your google login component

**Comment by kennetpostigo** [comment]
Thank you @dashracer ! If you are interested I could add you as a collaborator to make improvements for the login components. I also have a linkedin component I never put on github bc swamped at work.

**Comment by addingama** [comment]
Sure @kennetpostigo ,

This is my first time contributing to public repo :D

**Comment by kennetpostigo** [comment]
@dashracer Awesome! No worries 🙂 I made both the login components really quickly bc my job at the time gave me a tight deadline. So they are both a little rough around the edges but pretty stable all around. I'll add you as a collaborator, all I ask is not to push to master for improvements. Make a branch and then create a PR so that I can review the improvements.

**Comment by addingama** [comment]
I always create development branch in my repo.

So I create a pull request from my development branch to your master branch or to your development branch?

**Comment by kennetpostigo** [comment]
Yep! Okay so I just added you as a collaborator to both facebook and google login components. You have to confirm through email. I have a few things that I want to change about both of these projects that we can chat about tomorrow if you can.

**Comment by addingama** [comment]
okay, thanks @kennetpostigo

**Comment by kennetpostigo** [comment]
@dashracer Is this issue okay to close? if yes then we can use this issue to chat about changes tomorrow.

**Comment by addingama** [comment]
yes it's okay
